name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: "22"

      # Install dependencies
      - run: npm install
        working-directory: ./profile-app-be

      # Run Prisma generate
      - run: npx prisma generate
        working-directory: ./profile-app-be

      # Run tests
      - run: npm test
        working-directory: ./profile-app-be
